name: Github Action

on:
    push:
        branches: [develop]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: action/checkout@v1
            - name: set up JDK 11
                   with:
                     java-version: '11'
                     distribution: 'temurin'
                 - name: Build project
                   run: .github/scripts/gradlew_recursive.sh assembleDebug
                 - name: Zip artifacts
                   run: zip -r assemble.zip . -i '**/build/*.apk' '**/build/*.aab' '**/build/*.aar' '**/build/*.so'
                 - name: Upload artifacts
                   uses: actions/upload-artifact@v1
                   with:
                     name: assemble
                     path: assemble.zip